src/ToDo/urls.py
from django.contrib import admin
from django.contrib.auth import views as authviews
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from tasks.views import mainview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainview, name="mainview"),
    path('tasks/', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('login/', authviews.LoginView.as_view(template_name = "users/login.html"), name = 'login'),
    path('logout/', authviews.LogoutView.as_view(template_name = "users/logout.html"), name ='logout'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/tasks/urls.py
from django.urls import path
from .views import (
    home_view,
    create_task_view,
    update_task_view,
    task_detail_view, 
    delete_task_view
)

app_name = "tasks"
urlpatterns = [
    path('', home_view, name="homeview"),
    path('createtask/', create_task_view, name="createtask"),
    path('<int:id>/', task_detail_view, name="taskdetail"),
    path('updatetask/<int:id>', update_task_view, name="updatetask"),
    path('deletetask/<int:id>', delete_task_view, name="deletetask")
]

src/users/urls.py
from django.urls import path
from .views import (
    register_view, 
    profile_view,
)

app_name = "users"
urlpatterns = [
    path('register/', register_view, name="registeruser"),
    path('profile/', profile_view, name='profile'),
]

src/tasks/models.py
from django.db import models
from django.db.models.base import Model
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField(blank=True, null=False)
    completed = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('tasks:taskdetail', kwargs = {"id":self.id})

src/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE, blank=True, null=False)
    image = models.ImageField(default = "default.jpg", upload_to = 'profile_pictures')

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 300 or   img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

src/tasks/forms.py
from django.forms import fields, ModelForm
from .models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'content', 'completed']

src/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import fields
from django.forms.fields import EmailField
from .models import Profile

class UserRegistrationForm(UserCreationForm):
    email = EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

src/tasks/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Task
from .forms import TaskForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseForbidden
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
# Create your views here.

@login_required
def home_view(request):

    search_input = request.GET.get('search') or ''
    if search_input:
        all_tasks = Task.objects.filter(user=request.user, title__icontains = search_input) 
        # context = {
        # "tasks": all_tasks
        # } 
        # return render(request, 'tasks/home.html', context)

    else:
        all_tasks = Task.objects.filter(user=request.user)

    
    # context = {
    #     "tasks": all_tasks
    # } 

    paginator = Paginator(all_tasks, 1) 
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    context = {
        'page_obj': page_obj
    }

    return render(request, 'tasks/home.html', context)

@login_required
def task_detail_view(request, id):
    obj = get_object_or_404(Task, id=id)

    if obj.user == request.user:
        context = {
        "task":obj
        }
        return render(request, 'tasks/task_detail.html', context)
    else:
        #raise PermissionDenied("You do not have permission to view this task")
        return HttpResponseForbidden()


@login_required
def create_task_view(request):

    form = TaskForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            #form.save()
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            return redirect("../")
    
    context = {
        "form":form
    }

    return render(request, "tasks/create_task.html", context)

@login_required  
def update_task_view(request, id):
    obj = get_object_or_404(Task, id=id)
    if obj.user!= request.user:
        #raise PermissionDenied("You do not have permission to update this task")
        return HttpResponseForbidden()

    else:
        form = TaskForm(request.POST or None, instance=obj)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                return redirect("../")
        
        context = {
            "form":form
        }

        return render(request, "tasks/create_task.html", context)

@login_required
def delete_task_view(request, id):
    obj = get_object_or_404(Task, id=id)

    if obj.user!= request.user:
        #raise PermissionDenied("You do not have permission to update this task")
        return HttpResponseForbidden()

    else:
        if request.method == "POST":
            obj.delete()
            return redirect("../")

        context = {
            "task":obj
        }

        return render(request, "tasks/delete_task.html", context)

def mainview(request):
    return render(request, "tasks/main_view.html", {})

src/users/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def register_view(request):

    form = UserRegistrationForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'{username}, your account is created, now you can log in!')
            return redirect('login')
    context = {
        "form":form
    }
    return render(request, 'users/register.html', context)

@login_required
def profile_view(request):
   
    if request.method == "POST":
        user_form = UserUpdateForm(request.POST, instance = request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid() and user_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, f"Your account is updated succesfully!")
            return redirect("users:profile")

    else:
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        "user_form":user_form,
        "profile_form":profile_form
    }

    return render(request, "users/profile.html", context)

src/tasks/templates/tasks/create_task.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <h1 style="color:#126e82;">Create Task</h1>
    <div class="border-top pt-3">
        <form action="", method="POST">{% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-outline-success" type="submit">Save</button>
        </form>
    </div>
</div>
{% endblock%}

src/tasks/templates/tasks/delete_task.html
{% extends "base.html" %}

{% block content %}
<br/>
<br/>
<div class="container">
    <h1 style="color:#126e82;">Delete Task</h1>
    <div class="border-top pt-3">
        <form action="", method="POST">{% csrf_token %}
            <fieldset class="form-group">
                <h4>Are you sure you want to delete {{task.title}} ? </h4>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes</button>
                <a class="btn btn-outline-secondary" href="../">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

src/tasks/templates/tasks/home.html
{% extends "base.html" %}

{% block content %}{% csrf_token %}
<br/>

<div class="container">
    <h1 style="color:#126e82;">{{user.username}}'s Tasks</h1>
    <div class="border-top pt-3">
      <nav class="navbar navbar-light bg-light">
          <div class="container-fluid">
            <form class="d-flex" method="GET">
              <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </nav>

<br/>

<ol class="list-group list-group-numbered">
    {% for task in page_obj.object_list %}
        {% if task.completed == True %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <strike><div class="fw-bold"><a style="color: #000000;" href="{% url 'tasks:taskdetail' task.id %}" >{{task.title}}</a></div></strike>
            <br/>
            <a class="btn btn-outline-info btn-sm" href="{% url 'tasks:updatetask' task.id %}" role="button">Update</a>
            <a class="btn btn-outline-danger btn-sm" href="{% url 'tasks:deletetask' task.id %}" role="button">Delete</a>
          </div>
          <span class="badge bg-primary rounded-pill">{{task.date_modified}}</span>
        </li>
        {% else %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
              <div class="fw-bold"><a style="color: #000000;" href="{% url 'tasks:taskdetail' task.id %}" >{{task.title}}</a></div>
              <br/>
              <a class="btn btn-outline-info btn-sm" href="{% url 'tasks:updatetask' task.id %}" role="button">Update</a>
              <a class="btn btn-outline-danger btn-sm" href="{% url 'tasks:deletetask' task.id %}" role="button">Delete</a>
            </div>
            <span class="badge bg-primary rounded-pill">{{task.date_modified}}</span>
          </li>
        {% endif %}
    {% endfor %}
    </ol>


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</div>
</div>
{% endblock %}
    
    

src/tasks/templates/tasks/main_view.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 style="color:#126e82;">Welcome to ToDo App</h1>
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary btn-sm" href="{% url 'tasks:homeview' %}" role="button">ToDo things</a>
    {% else %}
    <h3 style="color:#126e82;">Register or Login to continue</h3>
    <a class="btn btn-outline-primary btn-sm" href="{% url 'users:registeruser' %}" role="button">Register</a>
    <a class="btn btn-outline-primary btn-sm" href="{% url 'login' %}" role="button">Login</a> 
    {% endif %}
</div>
{% endblock %}

src/tasks/templates/tasks/task_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1 style="color:#126e82;">Task Details</h1>
        <div class="border-top pt-3">
            {% if task.completed == True %}
            <h3>{{task.title}} is already completed. Do you wish to delete it?</h3>
            <a class="btn btn-outline-danger" href="{% url 'tasks:deletetask' task.id %}">Delete</a>
            <a class="btn btn-outline-primary" href="{% url 'tasks:updatetask' task.id%}">Update</a>
            <a class="btn btn-outline-info" href="../">Go Back</a>
            {% else %}
            <div>
                <h3>ToDo:  {{task.title}}</h3>
                <p class="text-break">{{task.content}}</p>
                <p class="text-muted">Date Modified: {{task.date_modified}}</p>
                <a class="btn btn-outline-danger" href="{% url 'tasks:deletetask' task.id %}">Delete</a>
                <a class="btn btn-outline-primary" href="{% url 'tasks:updatetask' task.id%}">Update</a>
                <a class="btn btn-outline-info" href="../">Go Back</a>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/templates/base.html
<!doctype html>
<html>
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <title>ToDo App</title>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
            <div class="container-fluid">
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                 {% if request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tasks:homeview' %}">All Tasks</a>
                  </li>
                  <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'tasks:createtask' %}">Create Task</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="{% url 'users:profile' %}">Profile</a>
                    </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'users:registeruser' %}">Register</a>
                  </li>
                  {% endif %}
                </ul>
                <form class="d-flex">
                  {% if request.user.is_authenticated %}
                  <a class="btn btn-outline-primary btn-sm" href="{% url 'logout' %}" role="button">Logout</a>
                  {% else %}
                  <a class="btn btn-outline-primary btn-sm" href="{% url 'login' %}" role="button">Login</a>   
                  {% endif %}               
                </form>
              </div>
            </div>
          </nav>
    </head>
    <body>
        {%for message in messages %}
        <p>{{message}}</p>
        {% endfor %}
        {% block content %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

src/users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br/>
<br/>
<div class="container">
    <h1 style="color:#126e82;">Login</h1>
    <div class="border-top pt-3">
        <div class="col-md-4 col-md-offset-4">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy}}
                <br/>
                <button class="btn btn-outline-success" type="submit">Login</button>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{% url 'users:registeruser' %}">Sign Up Now</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/users/templates/users/logout.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2 style="color:#126e82;">You are logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="btn btn-outline-info" href="{% url 'login' %}">Login again</a>
        </small>  
    </div> 
</div>
{% endblock %}

src/users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class ="row justify-content-around">
        <div class="col-4">
            <h1 style="color:#126e82;">Your Profile</h1>
            <div class="border-top pt-3">
                <h5>Username: {{user.username}}</h6>
                <h5>EmailID: {{user.email}}</h5>
                <div>
                    <img src="{{request.user.profile.image.url}}">
                </div>
            </div>   
        </div>
        <div class="col-8">
            <h1 style="color:#126e82;">Update Profile</h1>
            <div class="border-top pt-3">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
            
                    {{user_form|crispy}}
                    {{profile_form|crispy}}
                    <br/>
                    <button class="btn btn-outline-success" type="submit">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br/>
<div class="container">
    <h1 style="color:#126e82;">Register</h1>
    <div class="border-top pt-3">
        <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-outline-success" type="submit">Register</button>
        </form>
    </div>
</div>
{% endblock %}